
local shake_time
local shake  -- function



function init(self)
	self.pos = go.get_position()
	go.set_scale(.4)
	go.animate(".", "scale", go.PLAYBACK_LOOP_PINGPONG, vmath.vector3(.52, .52, 1), go.EASING_LINEAR, .8)
	msg.post("#sprite", "disable")
end




function on_message(self, message_id, message)
	if message_id == hash("detonate bomb") then
		msg.post(msg.url(nil, go.get_id(), "sprite"), "enable")
		sound.play("/sound#bomb_found")
		go.cancel_animations(".", "scale")
		go.set_scale(.4)
		shake_time = socket.gettime() + 1
		shake(self, 2)
		go.animate(".", "scale", go.PLAYBACK_LOOP_PINGPONG, vmath.vector3(.66, .66, 1), go.EASING_LINEAR, .33, 0, nil, go.PLAYBACK_LOOP_PINGPONG)
		go.set("#sprite", "tint", vmath.vector4(2,2,2,1))
		go.animate("#sprite", "tint", go.PLAYBACK_LOOP_PINGPONG, vmath.vector4(2,0,0,1), go.EASING_LINEAR, .2, 0, nil, go.PLAYBACK_LOOP_PINGPONG)
		timer.delay(1, false, function()
			msg.post("#sprite", "disable")
			go.cancel_animations(".", "scale")
			go.set_scale(2)
			sound.play("/sound#explode"..math.random(1, 2), {speed = proxy_speed})
			sound.play("/sound#explode_echo"..math.random(1, 2), {speed = proxy_speed, delay = .4})
			particlefx.play("#particles")
		end)

	elseif message_id == hash("reveal bomb") then
		timer.delay(1, false, function()
			if go.get_scale().z ~= 2 then
				msg.post(msg.url(nil, go.get_id(), "sprite"), "enable")
			end
		end)

	elseif message_id == hash("delete") then
		go.delete()
	end
end




function shake(self, distance)
	local pos = self.pos
	pos.x = pos.x + math.random(-distance, distance)
	pos.y = pos.y + math.random(-distance, distance)

	go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, pos, go.EASING_LINEAR, .1, 0, function()
		if socket.gettime() < shake_time then shake(self, distance) end
	end)
end
