
function init(self)
	msg.post(".", "disable")
	go.set_scale(1.72)
end




function on_message(self, message_id, message, sender)
	if message_id == hash("reveal digit") then
		local rotation

		if message.rot < 0 then
			rotation = 0 + message.rot
		else
			rotation = 0 - message.rot
		end
		go.set(".", "euler.z", rotation)
		msg.post(".", "enable")


	elseif message_id == hash("delete") then
		go.delete()
	end
end
