
local shake_allow
local shake  -- function



function init(self)
	shake_allow = true
	self.pos = go.get_position()
	go.set_scale(.4)
	go.animate(".", "scale", go.PLAYBACK_LOOP_PINGPONG, vmath.vector3(.52, .52, 1), go.EASING_LINEAR, .8)
	msg.post("#sprite", "disable")
end




function on_message(self, message_id, message)
	if message_id == hash("detonate bomb") then
		local pos = go.get_position()
		go.set_position(vmath.vector3(pos.x, pos.y, .5))
		shake_allow = false
		msg.post("#sprite", "disable")
		factory.create("/main#wave_factory")
		go.cancel_animations(".", "scale")
		go.set_scale(2)
		sound.play("/sound#explode"..math.random(1, 2), {speed = proxy_speed})
		sound.play("/sound#explode_echo"..math.random(1, 2), {speed = proxy_speed, delay = .4})
		particlefx.play("#particles")


	elseif message_id == hash("reveal bombs") then
		msg.post("#sprite", "enable")
		if message.is_clicked_bomb then
			local sprite_url = msg.url(nil, go.get_id(), "sprite")
			sound.play("/sound#bomb_found")
			go.set_scale(.36)
			shake(self, 2)
			go.animate(".", "scale", go.PLAYBACK_LOOP_PINGPONG, vmath.vector3(.64, .64, 1), go.EASING_LINEAR, .33, 0, nil, go.PLAYBACK_LOOP_PINGPONG)
			go.set("#sprite", "tint", vmath.vector4(2,2,2,1))
			go.animate(sprite_url, "tint", go.PLAYBACK_LOOP_PINGPONG, vmath.vector4(2,0,0,1), go.EASING_LINEAR, .2, 0, nil, go.PLAYBACK_LOOP_PINGPONG)
		end


	elseif message_id == hash("hide sprite") then
		msg.post("#sprite", "disable")


	elseif message_id == hash("delete") then
		go.delete()
	end
end




function shake(self, distance)
	local pos = vmath.vector3(self.pos)
	pos.x = pos.x + math.random(-distance, distance)
	pos.y = pos.y + math.random(-distance, distance)

	go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, pos, go.EASING_LINEAR, .2, 0, function()
		if shake_allow then shake(self, distance) end
	end)
end
